# This is a .comp file for requiring that a structure to have resonable amount of W and M
# File created 23 March 2020, Jingjia
PENALTY_DEFINITION
TYPE TRP
DELTA_START -1
DELTA_END 1
PENALTIES 0 0 100 # The above two lines mean that if we're 5% below or 5% above the desired content, we get a 100-point penalty.
ABSOLUTE 1 # Forty percent aromatic or aliphatic, but not leucine
BEFORE_FUNCTION CONSTANT
AFTER_FUNCTION CONSTANT
END_PENALTY_DEFINITION